ALTER TABLE `ChatMessage` CHANGE `userId` `userId` INT UNSIGNED NULL ;

CREATE TABLE `Token` (
`tokenId` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT ,
`name` VARCHAR( 150 ) NOT NULL ,
`image` VARCHAR( 255 ) NOT NULL ,
`active` TINYINT NOT NULL DEFAULT 1
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_unicode_ci ;